name: 'Build Corne QWERTY'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["crkbd"]'
      clipboard: '["mac"]'
      nav: '["vi"]'
      alphas: '["qwerty"]'
